/* Auto-generated config file - DO NOT EDIT */
#ifndef _PROJECT_CONFIG_H_
#define _PROJECT_CONFIG_H_

#define CONFIG_NETWORKING 1
#define CONFIG_TCP_SUPPORT 1
#define CONFIG_UDP_SUPPORT 1
#define CONFIG_FILE_OPERATIONS 1
#define CONFIG_PROJECT_VERSION_MAJOR 1
#define CONFIG_PROJECT_VERSION_MINOR 0

#endif /* _PROJECT_CONFIG_H_ */
